DNEXT-24540: add sample for ADMINReqDeleteInACL
HCL-TECH-SOFTWARE/domino-c-api-samples pull request #38
Opened 2023-12-20 11:56 UTC by shaiknayabrasool-s

2023-12-20 11:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/HCL-TECH-SOFTWARE/domino-c-api-samples?pullRequest=38) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/HCL-TECH-SOFTWARE/domino-c-api-samples?pullRequest=38) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: raghu-madat<br/>:white_check_mark: saravananbalakris<br/>:x: Shaik Nayab Rasool<br/><hr/>**Shaik Nayab Rasool** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/HCL-TECH-SOFTWARE/domino-c-api-samples?pullRequest=38) it.</sub>

2023-12-20 12:25 UTC, raghu-madat approved these changes

2023-12-21 07:00 UTC, vickum approved these changes
looks fine.

2023-12-21 08:30 UTC, saravananbalakris requested changes
Why there are 16 file changes present. Can you correct that.

2023-12-21 09:05 UTC, saravananbalakris approved these changes
Looks fine.

2023-12-21 09:18 UTC, raghu-madat approved these changes

2023-12-21 09:19 UTC, merged