DNEXT-24544: Add sample ADMIN API -ADMINReqRecertify
HCL-TECH-SOFTWARE/domino-c-api-samples pull request #48
Opened 2024-04-17 13:02 UTC by shaiknayabrasool-s

2024-04-17 13:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/HCL-TECH-SOFTWARE/domino-c-api-samples?pullRequest=48) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/HCL-TECH-SOFTWARE/domino-c-api-samples?pullRequest=48) before we can accept your contribution.<br/><hr/>**Shaik Nayab Rasool** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/HCL-TECH-SOFTWARE/domino-c-api-samples?pullRequest=48) it.</sub>

2024-04-17 14:23 UTC, raghu-madat requested changes
In  samples/admin/ADMINReqRecertify/linux64.mak
TARGET = ADMINReqRename is not correct.

2024-04-18 02:59 UTC, shaiknayabrasool-s commented
> In samples/admin/ADMINReqRecertify/linux64.mak TARGET = ADMINReqRename is not correct.

Modified

2024-04-18 04:19 UTC, raghu-madat approved these changes

2024-04-18 04:20 UTC, merged